Propagate errors from archive extraction
Means that instead of:

  $ etc /
  $ auracle download {auracle,systemd,pkgfile}-git
  download complete: /etc/pkgfile-git
  download complete: /etc/auracle-git
  download complete: /etc/systemd-git

We get:

  $ etc /
  $ auracle download {auracle,systemd,pkgfile}-git
  error: failed to extract tarball for auracle-git: Permission denied