Avoid throwing exception on AUR connection failure
Instead of:

terminate called after throwing an instance of 'nlohmann::detail::parse_error' [...]
Aborted (core dumped)

Now we get:

error: Failed to connect to aur.archlinux.org port 443: Connection timed out

Closes #37.